In [22]:
import numpy as np
import pandas as pd

In [23]:
dataset=pd.read_csv('wine.csv')

In [24]:
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
5               7.4             0.660         0.00             1.8      0.075   
6               7.9             0.600         0.06             1.6      0.069   
7               7.3             0.650         0.00             1.2      0.065   
8               7.8             0.580         0.02             2.0      0.073   
9               7.5             0.500         0.36             6.1      0.071   
10              6.7             0.580         0.08             1.8      0.097   
11              7.5             0.500         0.36             6.1      0.071   
12              5.6             0.615         0.00             1.6      0.089   
13              7.8             0.610         0.29             1.6      0.114   
14              8.9             0.620         0.18             3.8      0.176   
15              8.9             0.620         0.19             3.9      0.170   
16              8.5             0.280         0.56             1.8      0.092   
17              8.1             0.560         0.28             1.7      0.368   
18              7.4             0.590         0.08             4.4      0.086   
19              7.9             0.320         0.51             1.8      0.341   
20              8.9             0.220         0.48             1.8      0.077   
21              7.6             0.390         0.31             2.3      0.082   
22              7.9             0.430         0.21             1.6      0.106   
23              8.5             0.490         0.11             2.3      0.084   
24              6.9             0.400         0.14             2.4      0.085   
25              6.3             0.390         0.16             1.4      0.080   
26              7.6             0.410         0.24             1.8      0.080   
27              7.9             0.430         0.21             1.6      0.106   
28              7.1             0.710         0.00             1.9      0.080   
29              7.8             0.645         0.00             2.0      0.082   
...             ...               ...          ...             ...        ...   
1569            6.2             0.510         0.14             1.9      0.056   
1570            6.4             0.360         0.53             2.2      0.230   
1571            6.4             0.380         0.14             2.2      0.038   
1572            7.3             0.690         0.32             2.2      0.069   
1573            6.0             0.580         0.20             2.4      0.075   
1574            5.6             0.310         0.78            13.9      0.074   
1575            7.5             0.520         0.40             2.2      0.060   
1576            8.0             0.300         0.63             1.6      0.081   
1577            6.2             0.700         0.15             5.1      0.076   
1578            6.8             0.670         0.15             1.8      0.118   
1579            6.2             0.560         0.09             1.7      0.053   
1580            7.4             0.350         0.33             2.4      0.068   
1581            6.2             0.560         0.09             1.7      0.053   
1582            6.1             0.715         0.10             2.6      0.053   
1583            6.2             0.460         0.29             2.1      0.074   
1584            6.7             0.320         0.44             2.4      0.061   
1585            7.2             0.390         0.44             2.6      0.066   
1586            7.5             0.310

In [25]:
x=dataset.iloc[:,0:11].values

In [26]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [27]:
y=dataset.iloc[:,-1].values

In [28]:
y

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

In [29]:
x.ndim

2

In [30]:
y.ndim

1

In [31]:
x.shape

(1599, 11)

In [32]:
x.shape

(1599, 11)

In [33]:
from sklearn.model_selection import train_test_split                
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [34]:
x_train

array([[ 9.9 ,  0.54,  0.45, ...,  3.39,  0.62,  9.4 ],
       [10.8 ,  0.26,  0.45, ...,  3.13,  0.54,  9.6 ],
       [ 9.9 ,  0.35,  0.55, ...,  3.26,  0.79, 10.6 ],
       ...,
       [ 7.9 ,  0.57,  0.31, ...,  3.29,  0.69,  9.5 ],
       [13.  ,  0.47,  0.49, ...,  3.3 ,  0.68, 12.7 ],
       [ 9.8 ,  0.98,  0.32, ...,  3.25,  0.48,  9.4 ]])

In [35]:
x_train.shape

(1279, 11)

In [36]:
x_test

array([[10.8  ,  0.47 ,  0.43 , ...,  3.17 ,  0.76 , 10.8  ],
       [ 8.1  ,  0.82 ,  0.   , ...,  3.36 ,  0.53 ,  9.6  ],
       [ 9.1  ,  0.29 ,  0.33 , ...,  3.26 ,  0.84 , 11.7  ],
       ...,
       [ 9.1  ,  0.34 ,  0.42 , ...,  3.18 ,  0.55 , 11.4  ],
       [ 9.1  ,  0.765,  0.04 , ...,  3.29 ,  0.54 ,  9.7  ],
       [ 8.2  ,  0.32 ,  0.42 , ...,  3.27 ,  0.55 , 12.3  ]])

In [50]:
import keras 
from keras.models import Sequential 
from keras.layers import Dense 

In [38]:
model=Sequential()

In [39]:
x.shape

(1599, 11)

In [51]:
model.add(Dense(input_dim=11,init="random_uniform",activation="relu",output_dim=8)) 

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=8, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [52]:
model.add(Dense(output_dim=8,init="random_uniform",activation="relu"))

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [53]:
model.add(Dense(output_dim=1,init="random_uniform"))

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [54]:
model.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [55]:
model.fit(x_train,y_train,epochs=400,batch_size=10)

Epoch 1/400
1279/1279 [==============================] - 4s 3ms/step - loss: 27.6803 - mean_squared_error: 27.6803
Epoch 2/400
1279/1279 [==============================] - 0s 355us/step - loss: 3.4708 - mean_squared_error: 3.4708
Epoch 3/400
1279/1279 [==============================] - 0s 260us/step - loss: 1.8936 - mean_squared_error: 1.8936
Epoch 4/400
1279/1279 [==============================] - 0s 238us/step - loss: 0.9139 - mean_squared_error: 0.9139
Epoch 5/400
1279/1279 [==============================] - 0s 243us/step - loss: 0.5526 - mean_squared_error: 0.5526
Epoch 6/400
1279/1279 [==============================] - 0s 306us/step - loss: 0.5158 - mean_squared_error: 0.5158
Epoch 7/400
1279/1279 [==============================] - 0s 337us/step - loss: 0.5052 - mean_squared_error: 0.5052
Epoch 8/400
1279/1279 [==============================] - 0s 337us/step - loss: 0.5050 - mean_squared_error: 0.5050
Epoch 9/400
1279/1279 [==============================] - 0s 322us/step - loss: 0

1279/1279 [==============================] - 0s 351us/step - loss: 0.4487 - mean_squared_error: 0.4487
Epoch 72/400
1279/1279 [==============================] - 1s 520us/step - loss: 0.4492 - mean_squared_error: 0.4492
Epoch 73/400
1279/1279 [==============================] - 1s 444us/step - loss: 0.4440 - mean_squared_error: 0.4440
Epoch 74/400
1279/1279 [==============================] - 0s 344us/step - loss: 0.4400 - mean_squared_error: 0.4400
Epoch 75/400
1279/1279 [==============================] - 0s 377us/step - loss: 0.4472 - mean_squared_error: 0.4472
Epoch 76/400
1279/1279 [==============================] - 0s 348us/step - loss: 0.4416 - mean_squared_error: 0.4416
Epoch 77/400
1279/1279 [==============================] - 0s 350us/step - loss: 0.4446 - mean_squared_error: 0.4446
Epoch 78/400
1279/1279 [==============================] - 0s 356us/step - loss: 0.4506 - mean_squared_error: 0.4506
Epoch 79/400
1279/1279 [==============================] - 1s 392us/step - loss: 0.447

1279/1279 [==============================] - 0s 231us/step - loss: 0.4426 - mean_squared_error: 0.4426
Epoch 141/400
1279/1279 [==============================] - 0s 269us/step - loss: 0.4384 - mean_squared_error: 0.4384
Epoch 142/400
1279/1279 [==============================] - 0s 213us/step - loss: 0.4450 - mean_squared_error: 0.4450
Epoch 143/400
1279/1279 [==============================] - 0s 261us/step - loss: 0.4438 - mean_squared_error: 0.4438
Epoch 144/400
1279/1279 [==============================] - 0s 238us/step - loss: 0.4376 - mean_squared_error: 0.4376
Epoch 145/400
1279/1279 [==============================] - 0s 213us/step - loss: 0.4378 - mean_squared_error: 0.4378
Epoch 146/400
1279/1279 [==============================] - 0s 215us/step - loss: 0.4408 - mean_squared_error: 0.4408
Epoch 147/400
1279/1279 [==============================] - 0s 243us/step - loss: 0.4422 - mean_squared_error: 0.4422
Epoch 148/400
1279/1279 [==============================] - 0s 235us/step - los

1279/1279 [==============================] - 0s 353us/step - loss: 0.4413 - mean_squared_error: 0.4413
Epoch 210/400
1279/1279 [==============================] - 0s 354us/step - loss: 0.4409 - mean_squared_error: 0.4409
Epoch 211/400
1279/1279 [==============================] - 1s 455us/step - loss: 0.4411 - mean_squared_error: 0.44110s - loss: 0.4832 - mean_squ
Epoch 212/400
1279/1279 [==============================] - 0s 251us/step - loss: 0.4512 - mean_squared_error: 0.4512
Epoch 213/400
1279/1279 [==============================] - 0s 303us/step - loss: 0.4388 - mean_squared_error: 0.4388
Epoch 214/400
1279/1279 [==============================] - 0s 264us/step - loss: 0.4331 - mean_squared_error: 0.4331
Epoch 215/400
1279/1279 [==============================] - 0s 263us/step - loss: 0.4454 - mean_squared_error: 0.4454
Epoch 216/400
1279/1279 [==============================] - 0s 256us/step - loss: 0.4419 - mean_squared_error: 0.4419
Epoch 217/400
1279/1279 [=========================

1279/1279 [==============================] - 1s 630us/step - loss: 0.4355 - mean_squared_error: 0.4355
Epoch 276/400
1279/1279 [==============================] - 0s 316us/step - loss: 0.4385 - mean_squared_error: 0.4385
Epoch 277/400
1279/1279 [==============================] - 1s 595us/step - loss: 0.4356 - mean_squared_error: 0.4356
Epoch 278/400
1279/1279 [==============================] - 1s 532us/step - loss: 0.4343 - mean_squared_error: 0.4343
Epoch 279/400
1279/1279 [==============================] - 1s 637us/step - loss: 0.4399 - mean_squared_error: 0.4399
Epoch 280/400
1279/1279 [==============================] - 1s 412us/step - loss: 0.4413 - mean_squared_error: 0.4413
Epoch 281/400
1279/1279 [==============================] - 0s 285us/step - loss: 0.4446 - mean_squared_error: 0.4446
Epoch 282/400
1279/1279 [==============================] - 1s 554us/step - loss: 0.4455 - mean_squared_error: 0.4455
Epoch 283/400
1279/1279 [==============================] - 1s 580us/step - los

Epoch 342/400
1279/1279 [==============================] - 1s 509us/step - loss: 0.4441 - mean_squared_error: 0.4441
Epoch 343/400
1279/1279 [==============================] - 1s 497us/step - loss: 0.4387 - mean_squared_error: 0.4387
Epoch 344/400
1279/1279 [==============================] - 1s 532us/step - loss: 0.4340 - mean_squared_error: 0.43400s - loss: 0.4578 - mean_squared_error
Epoch 345/400
1279/1279 [==============================] - 1s 542us/step - loss: 0.4453 - mean_squared_error: 0.4453
Epoch 346/400
1279/1279 [==============================] - 1s 470us/step - loss: 0.4343 - mean_squared_error: 0.4343
Epoch 347/400
1279/1279 [==============================] - 1s 593us/step - loss: 0.4359 - mean_squared_error: 0.4359
Epoch 348/400
1279/1279 [==============================] - 1s 601us/step - loss: 0.4394 - mean_squared_error: 0.4394
Epoch 349/400
1279/1279 [==============================] - 1s 581us/step - loss: 0.4359 - mean_squared_error: 0.4359
Epoch 350/400
1279/1279 [=

In [56]:
model.predict(x_test)

array([[5.923464 ],
       [5.1613917],
       [6.6650376],
       [5.426355 ],
       [6.011552 ],
       [5.0016646],
       [5.397142 ],
       [6.2399726],
       [4.916207 ],
       [4.97608  ],
       [5.3446245],
       [5.504292 ],
       [5.8601756],
       [5.239451 ],
       [5.6239924],
       [6.4418616],
       [6.8781433],
       [5.825886 ],
       [6.086123 ],
       [5.1635776],
       [6.382829 ],
       [5.3006544],
       [5.736061 ],
       [5.995776 ],
       [5.6905065],
       [5.0794406],
       [5.216829 ],
       [6.5859075],
       [5.329408 ],
       [6.5301604],
       [6.1203094],
       [5.968601 ],
       [5.742144 ],
       [5.4644694],
       [5.9007964],
       [6.356276 ],
       [5.2526793],
       [5.740559 ],
       [6.548393 ],
       [5.890405 ],
       [5.5617404],
       [6.1479106],
       [6.660622 ],
       [6.6905174],
       [6.057349 ],
       [4.753754 ],
       [5.4678283],
       [6.107224 ],
       [5.705051 ],
       [6.197411 ],


In [57]:
x_test

array([[10.8  ,  0.47 ,  0.43 , ...,  3.17 ,  0.76 , 10.8  ],
       [ 8.1  ,  0.82 ,  0.   , ...,  3.36 ,  0.53 ,  9.6  ],
       [ 9.1  ,  0.29 ,  0.33 , ...,  3.26 ,  0.84 , 11.7  ],
       ...,
       [ 9.1  ,  0.34 ,  0.42 , ...,  3.18 ,  0.55 , 11.4  ],
       [ 9.1  ,  0.765,  0.04 , ...,  3.29 ,  0.54 ,  9.7  ],
       [ 8.2  ,  0.32 ,  0.42 , ...,  3.27 ,  0.55 , 12.3  ]])

In [58]:
y_test

array([6, 5, 7, 6, 5, 6, 5, 6, 4, 5, 5, 5, 6, 5, 6, 6, 7, 5, 5, 4, 7, 6,
       6, 4, 6, 5, 5, 7, 5, 6, 5, 6, 5, 6, 7, 7, 5, 6, 6, 7, 5, 7, 6, 6,
       5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6,
       5, 5, 6, 6, 6, 6, 4, 6, 5, 6, 5, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 4, 5, 7, 6, 6, 5, 6, 5, 8, 6, 6, 6, 5, 5, 5, 5, 7, 5,
       6, 5, 7, 5, 6, 6, 6, 7, 6, 6, 5, 7, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6,
       6, 6, 6, 5, 6, 5, 8, 5, 6, 5, 6, 5, 4, 6, 7, 6, 5, 6, 6, 5, 5, 5,
       6, 6, 3, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 8, 5, 6,
       6, 7, 7, 5, 5, 7, 5, 6, 6, 4, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 7, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5,
       5, 5, 6, 6, 5, 6, 6, 6, 3, 6, 5, 5, 7, 6, 7, 6, 6, 7, 7, 6, 5, 6,
       5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 6, 7, 5, 6, 5, 6,
       5, 4, 5, 5, 6, 7, 6, 5, 5, 4, 5, 6, 7, 6, 6, 7, 5, 7, 5, 6, 6, 5,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 6,

In [59]:
model.predict(np.array([[11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8]]))

array([[5.8131423]], dtype=float32)

In [60]:
model.predict(np.array([[7.4,0.7,0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4]]))

array([[5.219055]], dtype=float32)